# Generated by Django 4.1.7 on 2023-03-23 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('R', 'Records'), ('C', 'Clothes'), ('P', 'Posters'), ('M', 'Miscellaneous')], default='R', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2035)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
